// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  main_benefits: dynamic(() => import("./Benefits")),
  main_call_to_action: dynamic(() => import("./CallToAction")),
  main_faq: dynamic(() => import("./Faq")),
  main_featured: dynamic(() => import("./FeaturedContent")),
  main_features: dynamic(() => import("./Features")),
  main_form: dynamic(() => import("./Form")),
  main_hero: dynamic(() => import("./Hero")),
  main_how_it_works: dynamic(() => import("./HowItWorks")),
  main_jobs: dynamic(() => import("./Jobs")),
  main_logotypes: dynamic(() => import("./Logotypes")),
  main_pricing: dynamic(() => import("./Pricing")),
  main_spacer: dynamic(() => import("./Spacer")),
  main_testimonials: dynamic(() => import("./Testimonials")),
  main_text_media: dynamic(() => import("./TextMedia"))
};
